spring.application.name=backend-craft

# MySQL connection
spring.datasource.url=jdbc:mysql://localhost:3306/backenddb
spring.datasource.username=root
spring.datasource.password=Kavya@2004

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect